name: 自动签到海绵联机

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *' # 每天一次，UTC 时间早上 6 点运行（即北京时间下午 2 点）
  workflow_dispatch:

jobs:
  read-and-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 从文件读取需要签到的ID
      run: |
        sudo apt-get install -y jq
        uid_list=$(jq -r '.[]' hmmc.json)
        for uid in $uid_list; do
          echo "即将签到用户: $uid"
          response=$(curl -s -k -X POST -d "uid=${uid}" "https://www.yunmc.vip/addons?_plugin=8&_controller=index&_action=index")
          msg=$(echo "$response" | jq -r '.msg')
          echo "用户 $uid : $msg"
        done
